[files]
extend-exclude = [
    "docs/nl/",
    "docs/.vitepress/nl.ts",
    "docs/pt/",
    "docs/.vitepress/pt.ts",
    "docs/zh_cn/",
    "docs/.vitepress/zh_cn.ts",
    "docs/de/",
    "docs/.vitepress/de.ts",
    "docs/tr_TR/",
    "docs/.vitepress/tr_tr.ts",
    "docs/ja_jp/",
    "docs/.vitepress/ja_jp.ts",
    "docs/fr/",
    "docs/.vitepress/fr.ts",

]

[default.extend-words]
Iinclude = "Iinclude"
